name: Test Dev

on:
  push:
    branches:
      - dev

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    container: node:14.16-slim

    services:
      redis:
        image: redis:6.2-alpine

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Test
        env:
          REDIS_URI: redis://redis:6379
        run: npm run test
